---
prometheus_collector_user: prometheus
prometheus_collector_root: /opt/prometheus
prometheus_collector_data_dir: /var/lib/prometheus
prometheus_collector_port: 9090
prometheus_collector_arch_map:
  x86_64: amd64
  aarch64: arm64
prometheus_collector_checksums:
  amd64: 2a542df32eac02ee17b9d844fb2aa1de00dafa5476579ba8a3ba862e9d572ea0
  arm64: f1f90ec08e849d494ca66c611470afc50192f0355f1a61c33f2cbde02d067823
