---
all:
  vars:
    ansible_user: azureuser
    ansible_ssh_common_args: "-o IdentitiesOnly=yes"
  children:
    zava_workloads:
      hosts:
        rhel-db:
          ansible_host: 192.168.90.11
          zava_tier: db
        sles-api:
          ansible_host: 192.168.90.12
          zava_tier: api
        ubuntu-web:
          ansible_host: 192.168.90.13
          zava_tier: web
        ciq-rocky-worker:
          ansible_host: 192.168.90.14
          zava_tier: worker
    zava_api:
      hosts:
        sles-api:
    zava_database:
      hosts:
        rhel-db:
    zava_workers:
      hosts:
        ciq-rocky-worker:
    prometheus_collectors:
      hosts:
        zava-cutover-admin:
          ansible_host: 192.168.90.10
          zava_tier: observability
